import { Client, Room } from 'colyseus';
import { issueDevelopmentIdentity } from '../auth/development-identity.js';
import { logger } from '../logging/logger.js';
import { simulate, spawnBody, type Body } from '../movement/simulation.js';
import { ClientMessages, InputStateSchema, type InputState, type JoinOptions } from '../networking/protocol.js';
import { permitInput, releaseInputGuard } from '../security/input-guard.js';
import { PlayerState, TestRoomState } from './schema.js';
export class DevelopmentRoom extends Room{declare state:TestRoomState;maxClients=50;private readonly bodies=new Map<string,Body>();private readonly pendingInputs=new Map<string,InputState>();private fixedStep=1/60;
  onCreate():void{this.setState(new TestRoomState());this.setSimulationInterval(dt=>this.update(dt/1000),1000/60);this.onMessage(ClientMessages.input,(client,payload)=>this.acceptInput(client,payload));this.onMessage(ClientMessages.heartbeat,(client)=>client.send('heartbeat_ack',{serverTime:Date.now()}));this.onMessage(ClientMessages.leave,client=>client.leave());logger.info({roomId:this.roomId,zoneId:this.state.zoneId},'room_created');}
  onJoin(client:Client,options:JoinOptions):void{const identity=issueDevelopmentIdentity(options.developmentName);client.userData=identity;const body=spawnBody(this.clients.length*55);const state=new PlayerState();state.playerId=identity.playerId;this.bodies.set(client.sessionId,body);this.pendingInputs.set(client.sessionId,{sequence:0,left:false,right:false,jump:false,clientTime:0});this.state.players.set(client.sessionId,state);logger.info({roomId:this.roomId,sessionId:client.sessionId,playerId:identity.playerId},'player_joined');}
  onLeave(client:Client):void{this.bodies.delete(client.sessionId);this.pendingInputs.delete(client.sessionId);this.state.players.delete(client.sessionId);releaseInputGuard(client.sessionId);logger.info({roomId:this.roomId,sessionId:client.sessionId,playerId:client.userData?.playerId},'player_left');}
  private acceptInput(client:Client,payload:unknown):void{if(!permitInput(client)){logger.warn({sessionId:client.sessionId},'input_rate_limited');return;}const result=InputStateSchema.safeParse(payload);if(!result.success){logger.warn({sessionId:client.sessionId,issues:result.error.issues.map(i=>i.code)},'invalid_input');return;}const prior=this.pendingInputs.get(client.sessionId);if(!prior||result.data.sequence<=prior.sequence)return;if(result.data.left&&result.data.right)result.data.right=false;this.pendingInputs.set(client.sessionId,result.data);}
  private update(delta:number):void{this.fixedStep=1/60;this.state.serverTick++;for(const [sessionId,body] of this.bodies){const input=this.pendingInputs.get(sessionId);const player=this.state.players.get(sessionId);if(!input||!player)continue;simulate(body,input,Math.min(delta,this.fixedStep*3));player.x=body.x;player.y=body.y;player.vx=body.vx;player.vy=body.vy;player.grounded=body.grounded;player.facing=body.facing;player.lastProcessedInputSequence=body.lastProcessedInputSequence;player.animation=body.grounded?(Math.abs(body.vx)>5?'run':'idle'):(body.vy<0?'jump':'fall');}}
}
